'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSCorreiosPreco
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSCorreiosPreco.CalcPrecoPrazoWSSoap")>  _
    Public Interface CalcPrecoPrazoWSSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazo(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazo", ReplyAction:="*")>  _
        Function CalcPrecoPrazoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoData", ReplyAction:="*")>  _
        Function CalcPrecoPrazoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoRestricao", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazoRestricao(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoRestricao", ReplyAction:="*")>  _
        Function CalcPrecoPrazoRestricaoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPreco", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPreco(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPreco", ReplyAction:="*")>  _
        Function CalcPrecoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoData", ReplyAction:="*")>  _
        Function CalcPrecoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazo(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazo", ReplyAction:="*")>  _
        Function CalcPrazoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazoData(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoData", ReplyAction:="*")>  _
        Function CalcPrazoDataAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoRestricao", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazoRestricao(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoRestricao", ReplyAction:="*")>  _
        Function CalcPrazoRestricaoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoFAC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoFAC(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As WSCorreiosPreco.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoFAC", ReplyAction:="*")>  _
        Function CalcPrecoFACAsync(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private servicosField() As cServico
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Servicos() As cServico()
            Get
                Return Me.servicosField
            End Get
            Set
                Me.servicosField = value
                Me.RaisePropertyChanged("Servicos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cServico
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As Integer
        
        Private valorField As String
        
        Private prazoEntregaField As String
        
        Private valorMaoPropriaField As String
        
        Private valorAvisoRecebimentoField As String
        
        Private valorValorDeclaradoField As String
        
        Private entregaDomiciliarField As String
        
        Private entregaSabadoField As String
        
        Private erroField As String
        
        Private msgErroField As String
        
        Private valorSemAdicionaisField As String
        
        Private obsFimField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("Valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property PrazoEntrega() As String
            Get
                Return Me.prazoEntregaField
            End Get
            Set
                Me.prazoEntregaField = value
                Me.RaisePropertyChanged("PrazoEntrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ValorMaoPropria() As String
            Get
                Return Me.valorMaoPropriaField
            End Get
            Set
                Me.valorMaoPropriaField = value
                Me.RaisePropertyChanged("ValorMaoPropria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ValorAvisoRecebimento() As String
            Get
                Return Me.valorAvisoRecebimentoField
            End Get
            Set
                Me.valorAvisoRecebimentoField = value
                Me.RaisePropertyChanged("ValorAvisoRecebimento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ValorValorDeclarado() As String
            Get
                Return Me.valorValorDeclaradoField
            End Get
            Set
                Me.valorValorDeclaradoField = value
                Me.RaisePropertyChanged("ValorValorDeclarado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property EntregaDomiciliar() As String
            Get
                Return Me.entregaDomiciliarField
            End Get
            Set
                Me.entregaDomiciliarField = value
                Me.RaisePropertyChanged("EntregaDomiciliar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property EntregaSabado() As String
            Get
                Return Me.entregaSabadoField
            End Get
            Set
                Me.entregaSabadoField = value
                Me.RaisePropertyChanged("EntregaSabado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Erro() As String
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
                Me.RaisePropertyChanged("Erro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property MsgErro() As String
            Get
                Return Me.msgErroField
            End Get
            Set
                Me.msgErroField = value
                Me.RaisePropertyChanged("MsgErro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property ValorSemAdicionais() As String
            Get
                Return Me.valorSemAdicionaisField
            End Get
            Set
                Me.valorSemAdicionaisField = value
                Me.RaisePropertyChanged("ValorSemAdicionais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property obsFim() As String
            Get
                Return Me.obsFimField
            End Get
            Set
                Me.obsFimField = value
                Me.RaisePropertyChanged("obsFim")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalcPrecoPrazoWSSoapChannel
        Inherits WSCorreiosPreco.CalcPrecoPrazoWSSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalcPrecoPrazoWSSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSCorreiosPreco.CalcPrecoPrazoWSSoap)
        Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CalcPrecoPrazo(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazo
            Return MyBase.Channel.CalcPrecoPrazo(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoPrazoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazoAsync
            Return MyBase.Channel.CalcPrecoPrazoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoPrazoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazoData
            Return MyBase.Channel.CalcPrecoPrazoData(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrecoPrazoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazoDataAsync
            Return MyBase.Channel.CalcPrecoPrazoDataAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrecoPrazoRestricao(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazoRestricao
            Return MyBase.Channel.CalcPrecoPrazoRestricao(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrecoPrazoRestricaoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoPrazoRestricaoAsync
            Return MyBase.Channel.CalcPrecoPrazoRestricaoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPreco(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPreco
            Return MyBase.Channel.CalcPreco(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoAsync
            Return MyBase.Channel.CalcPrecoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoData
            Return MyBase.Channel.CalcPrecoData(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrecoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoDataAsync
            Return MyBase.Channel.CalcPrecoDataAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrazo(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazo
            Return MyBase.Channel.CalcPrazo(nCdServico, sCepOrigem, sCepDestino)
        End Function
        
        Public Function CalcPrazoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazoAsync
            Return MyBase.Channel.CalcPrazoAsync(nCdServico, sCepOrigem, sCepDestino)
        End Function
        
        Public Function CalcPrazoData(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazoData
            Return MyBase.Channel.CalcPrazoData(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrazoDataAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazoDataAsync
            Return MyBase.Channel.CalcPrazoDataAsync(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrazoRestricao(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazoRestricao
            Return MyBase.Channel.CalcPrazoRestricao(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrazoRestricaoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrazoRestricaoAsync
            Return MyBase.Channel.CalcPrazoRestricaoAsync(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrecoFAC(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As WSCorreiosPreco.cResultado Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoFAC
            Return MyBase.Channel.CalcPrecoFAC(nCdServico, nVlPeso, strDataCalculo)
        End Function
        
        Public Function CalcPrecoFACAsync(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As System.Threading.Tasks.Task(Of WSCorreiosPreco.cResultado) Implements WSCorreiosPreco.CalcPrecoPrazoWSSoap.CalcPrecoFACAsync
            Return MyBase.Channel.CalcPrecoFACAsync(nCdServico, nVlPeso, strDataCalculo)
        End Function
    End Class
End Namespace
